export const productData = [
  {
    id: 1,
    title: "AMG G63",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.",
    category: "Luxury",
    brand: "Mercedes",
    img: "https://www.rentluxurycars.ae/wp-content/uploads/2023/05/Rent-Rolls-Royce-Cullinun-700x466.jpeg",
    alt: "AMG G63",
    priceRange: "43999",
  },
  {
    id: 2,
    title: "Urus",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.",
    category: "Luxury",
    brand: "Lamborghini",
    img: "https://www.rentluxurycars.ae/wp-content/uploads/2023/09/G63-White-700x466.jpeg",
    alt: "Urus",
    priceRange: "95999",
  },
  {
    id: 3,
    title: "Cullinan",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.",
    category: "Convertible",
    brand: "Rolls Royce",
    img: "https://www.rentluxurycars.ae/wp-content/uploads/2022/05/Rent-Urus-in-Dubai-700x466.jpg",
    alt: "Cullinan",
    priceRange: "109299",
  },
  // {
  //     id: 4,
  //     title: 'Car Name',
  //     desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.',
  //     category: 'Luxury',
  //     brand: 'BMW',
  //     img: "",
  //     priceRange: '120',
  // },
  // {
  //     id: 5,
  //     title: 'Car Name',
  //     desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.',
  //     category: 'Luxury',
  //     brand: 'BMW',
  //     img: "",
  //     priceRange: '120',
  // },
  // {
  //     id: 6,
  //     title: 'Car Name',
  //     desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.',
  //     category: 'Sports',
  //     brand: 'BMW',
  //     img: "",
  //     priceRange: '120',
  // },
  // {
  //     id: 7,
  //     title: 'Car Name',
  //     desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.',
  //     category: 'Luxury',
  //     brand: 'BMW',
  //     img: "",
  //     priceRange: '120',
  // },
  // {
  //     id: 8,
  //     title: 'Car Name',
  //     desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque assumenda quasi eveniet, exercitationem earum laboriosam ipsa aut sapiente quos harum cumque officia molestias laborum a dolorem consequatur in quis nesciunt.',
  //     category: 'Luxury',
  //     brand: 'BMW',
  //     img: "",
  //     priceRange: '120',
  // },
];
